### PR TITLE
Atlas probe viewer

### PR DESCRIPTION
**Pull request by petersaj**
fixed some stuff

### CODE REVIEW

**Comment by nsteinme** [comment]
There is a function in this repo called "allenCCFbregma" that returns my guess for the correct position - mind using that so if we get a true value at some point in the future then we can immediately apply it everywhere? I don't mind if you want to tweak the value I put there if you think I'm off. 

Otherwise is this done or are you still working on it? Just let me know when I should test.

**Comment by petersaj** [comment]
sure can replace the bregma function, I moved your estimate back 100 um -
and nope I'm done with it

**Comment by petersaj** [comment]
(should say I moved the estimate back where I hardcoded it, not in your
function)

**Comment by nsteinme** [comment]
Ok, great, so could you update the bregma function to reflect the value you like, then use the bregma function in your new code? Does it make sense? If you think this is stupid you don't have to do it, I just thought it was a good idea.

**Comment by petersaj** [comment]
ok did both on the branch

**Comment by nsteinme** [comment]
finally merged this - you can use master now! sorry for the delay

**Pull request merged**
